#!/bin/bash -l
source .language
APPNAME="$(basename ${0})"
# TERMINAL
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
WHITE="$(tput setaf 7)"
CYAN="$(tput setaf 6)"
UNDERLINE="$(tput sgr 0 1)"
BOLD="$(tput bold)"
NOCOLOR="$(tput sgr0)"
COLS="$(tput cols)"

CASEFILE="case.txt"
ANSWERFILE="answer.txt"
TESTDIR="$(pwd)/tests"
TESTFILES="${TESTDIR}/*"
VERSION=`git rev-parse --short HEAD`
SUBCOMMAND=${1:-usage}

function line() {
    while (( ${#LINE} < COLS ))
    do
        LINE="$LINE#"
    done

    echo "${LINE:0:$COLS}"
}

function run() {
    failed=''
    for dir in $TESTFILES; do
        output=`cat "${dir}/${CASEFILE}" | $language $target`
        answer=`cat ${dir}/${ANSWERFILE}`
        if [ "${output}" = "${answer}" ]; then
            /bin/echo -n "."
        else
            /bin/echo -n "x"
            failed="${failed},${dir}/case.txt"
        fi
    done
    echo
    if [ ${#failed} -eq 0 ]; then
        echo "${GREEN}All Test Green${NOCOLOR}"
    else
        echo "${RED}Failed Any TestCase${NOCOLOR}"
        arr=( `echo $failed | tr -s ',' ' '`)
        for fail in $arr; do
            echo "- $fail"
        done
    fi
}

function verbose() {
    for dir in $TESTFILES; do
        line
        echo "# ${CYAN}TEST CASE $(basename ${dir}) by `basename ${language}` ${NOCOLOR}"
        line
        output=`cat "${dir}/${CASEFILE}" | $language $target`
        answer=`cat ${dir}/${ANSWERFILE}`
        if [ "${output}" = "${answer}" ]; then
            echo "${GREEN}test ${dir}/case.txt success${NOCOLOR}"
            echo
            echo "${GREEN}- answer:${NOCOLOR}"
            echo "${answer}"
            echo
            echo "${RED}- output:${NOCOLOR}"
            echo "${output}"
            echo
        else
            echo "- ${RED}test ${dir}/case.txt faield case${NOCOLOR}"
            echo
            echo "answer:"
            echo "${answer}"
            echo
            echo "output:"
            echo "${output}"
            echo
        fi
    done
}

function clean() {
    for dir in $TESTFILES; do
        rm -rf $dir
    done
    echo "${GREEN}test cases removed${NOCOLOR}"
}

function new() {
    testname=${1}
    mkdir "${TESTDIR}/${testname}" && \
    echo > "${TESTDIR}/${testname}/${CASEFILE}" && \
    echo > "${TESTDIR}/${testname}/${ANSWERFILE}" && \
    echo "${GREEN}test directory create ${TESTDIR}/${testname} ${NOCOLOR}"
}

function add() {
    if [ ${#1} -eq 0 ]; then
        echo "${RED}testname is required!${NOCOLOR}"
        usage
    else
        if [ -e "$TESTDIR/$1" ]; then
            echo "${RED}\"$1\" testcase is exists!${NOCOLOR}"
            usage
        else
            new $1
        fi
    fi
}


function version {
    echo "${APPNAME} version ${VERSION} "
}

function usage() {
    cat <<EOF
${GREEN}
${APPNAME} is a tool for testing https://paiza.jp/

version ${VERSION}

Usage:
    ./${APPNAME} run
    ./${APPNAME} verbose
    ./
Command:
    add  [testname]   create tests direcotory increment folder name
    run               run all tests
    verbose           run all tests & show results
    clean             drop test cases
    version           print $(basename ${0}) version
    help              print this
${NOCOLOR}
EOF
}

case "$SUBCOMMAND" in
    run )
        run;
    ;;
    verbose )
        verbose;
    ;;
    clean )
        clean;
    ;;
    add )
        add ${2}
    ;;
    version|--version)
        version
    ;;
    usage|help|--help|-h )
        usage
    ;;
    *)
        echo "[ERROR] Invalid subcommand '${1}'"
        usage
        exit 1
    ;;
esac
